// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUV7NuhK9_XqgClLZAiukIV_qAPzDqm4M',
    appId: '1:437402016010:web:eab40e347bbc1451be82f3',
    messagingSenderId: '437402016010',
    projectId: 'unilink-r',
    authDomain: 'unilink-r.firebaseapp.com',
    storageBucket: 'unilink-r.firebasestorage.app',
    measurementId: 'G-S5Y738TFR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPRiQLmpBZXDOEz5beKIRDeJGdtlZd1KI',
    appId: '1:437402016010:android:fd78a2fcab147d18be82f3',
    messagingSenderId: '437402016010',
    projectId: 'unilink-r',
    storageBucket: 'unilink-r.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_pw1o_wlS7cWOac1yEFe-K5RMaa_sAIo',
    appId: '1:437402016010:ios:4b950c4480e79b5bbe82f3',
    messagingSenderId: '437402016010',
    projectId: 'unilink-r',
    storageBucket: 'unilink-r.firebasestorage.app',
    iosBundleId: 'com.example.cpofsad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_pw1o_wlS7cWOac1yEFe-K5RMaa_sAIo',
    appId: '1:437402016010:ios:4b950c4480e79b5bbe82f3',
    messagingSenderId: '437402016010',
    projectId: 'unilink-r',
    storageBucket: 'unilink-r.firebasestorage.app',
    iosBundleId: 'com.example.cpofsad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUV7NuhK9_XqgClLZAiukIV_qAPzDqm4M',
    appId: '1:437402016010:web:131f8fddd62cf4eebe82f3',
    messagingSenderId: '437402016010',
    projectId: 'unilink-r',
    authDomain: 'unilink-r.firebaseapp.com',
    storageBucket: 'unilink-r.firebasestorage.app',
    measurementId: 'G-ERRE087WYD',
  );
}
