import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // AUTO-GENERATED by: flutterfire configure

import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Connect to your specific database
  await Supabase.initialize(
    url: 'https://nmahirxmkbkktinjkdxa.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tYWhpcnhta2Jra3RpbmprZHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2Nzc4NDgsImV4cCI6MjA4ODI1Mzg0OH0.kN8jxCO0Csfc6-jYi1sBUpefr1d-a3MIdtJR5rd40as',
  );

  // Initialize Firebase for chat feature
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const UniLinkApp());
}

class UniLinkApp extends StatelessWidget {
  const UniLinkApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'UniLink',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        // We will use Google Fonts to make the app look premium instantly
        textTheme: GoogleFonts.poppinsTextTheme(),
        // Updated to match the deep indigo branding of the new login screen
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF2E3192)),
        useMaterial3: true,
      ),
      home: const AuthGatekeeper(),
    );
  }
}

// The Gatekeeper: Checks if a user is logged in
class AuthGatekeeper extends StatelessWidget {
  const AuthGatekeeper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<AuthState>(
      stream: Supabase.instance.client.auth.onAuthStateChange,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          // Upgraded to match the off-white premium background of the app
          return const Scaffold(
            backgroundColor: Color(0xFFF4F6F9),
            body: Center(
              child: CircularProgressIndicator(color: Color(0xFF2E3192)),
            ),
          );
        }

        final session = snapshot.data?.session;

        if (session != null) {
          // User is logged in! Go to the main dashboard.
          return const HomeScreen();
        } else {
          // User is NOT logged in. Go to Login Screen.
          return const LoginScreen();
        }
      },
    );
  }
}